/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cau_2.GUI;

import Cau_2.BUS.BacSiBUS;
import Cau_2.BUS.DichVuBUS;
import Cau_2.BUS.KhamBenhBUS;
import Cau_2.connection.OracleConnection;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author trant
 */
public class ChiTietKhamBenhGUI extends javax.swing.JFrame {

    private KhamBenhBUS khamBenhBUS;
    private BacSiBUS bacSiBUS;
    private DichVuBUS dichVuBUS;
    private String selectedTenBN = "";

    /**
     * Creates new form BenhNhanGUI
     */
    public ChiTietKhamBenhGUI() throws SQLException {
        bacSiBUS = new BacSiBUS();
        dichVuBUS = new DichVuBUS();
        initComponents();
        setTitle("Khám bệnh");
        loadTenBS();
        setTableDV();
        khamBenhBUS = new KhamBenhBUS();
        
        date_nkham.getDateEditor().getUiComponent().addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    try {
                        loadDSBenhNhan();
                    } catch (SQLException ex) {
                        Logger.getLogger(ChiTietKhamBenhGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        
//        combo_tenbn.addActionListener(new ActionListener() {
//        @Override
//        public void actionPerformed(ActionEvent e) {
//            try {
//                String mabn = layMaBN();
//                String mabs = layMaBS();
//                LocalDate ngKham = date_nkham.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
//                String selectedPatient = (String) combo_tenbn.getSelectedItem();
//                if (selectedPatient != null && !selectedPatient.isEmpty()) {
//                    String yeuCauKham = khamBenhBUS.layYeuCauKham(mabn, mabs, ngKham);
//                    txt_yckham.setText(yeuCauKham);
//                    txt_yckham.setEditable(false); // Ensure the text field is not editable
//                }
//            } catch (SQLException ex) {
//                ex.printStackTrace();
//                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//            }
//        }
//    });

    }
    
    private void loadTenBS() throws SQLException {
        List<String> danhSachTenBS = bacSiBUS.layDSTenBS();
        combo_tenbs.removeAllItems();
        for (String tenBS : danhSachTenBS) {
            combo_tenbs.addItem(tenBS);
        }
    }
    
    public void setTableDV() throws SQLException{
        DefaultTableModel tb = (DefaultTableModel) tb_dsdv.getModel();
        tb.setRowCount(0);
        List<String> dichVuList = dichVuBUS.layDSDV();
        for (String tendv : dichVuList) {
            tb.addRow(new Object[]{tendv});
        }
    }
    
    public String layMaBS() throws SQLException{
        String mabs = null;
        String tenbs = (String)combo_tenbs.getSelectedItem();
        mabs = bacSiBUS.layMaBS(tenbs);
        
        return mabs;
    }
    
    public String layMaBN() throws SQLException{
        String mabn = null;
        String mabs = layMaBS();
        java.util.Date selected_utilDate = date_nkham.getDate();
        String tenbn = (String)combo_tenbn.getSelectedItem();
        
        if (selected_utilDate != null) {
            java.sql.Date ngayKham_sqlDate = new java.sql.Date(selected_utilDate.getTime());

            mabn = khamBenhBUS.layMaBN(mabs, ngayKham_sqlDate, tenbn);
        }
        return mabn;
    }
    
    
    private void loadDSBenhNhan() throws SQLException {
        String mabs = layMaBS();
        java.util.Date selected_utilDate = date_nkham.getDate();
        if (selected_utilDate != null) {
            java.sql.Date ngayKhamSqlDate = new java.sql.Date(selected_utilDate.getTime());

            List<String> dsBenhNhan = khamBenhBUS.layBN(mabs, ngayKhamSqlDate);
            combo_tenbn.removeAllItems();
            for (String tenBN : dsBenhNhan) {
                combo_tenbn.addItem(tenBN);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_bs = new javax.swing.JLabel();
        lb_tenbn = new javax.swing.JLabel();
        lb_nkham = new javax.swing.JLabel();
        lb_yckham = new javax.swing.JLabel();
        lb_kluan = new javax.swing.JLabel();
        txt_yckham = new javax.swing.JTextField();
        combo_tenbs = new javax.swing.JComboBox<>();
        btn_kham = new javax.swing.JButton();
        date_nkham = new com.toedter.calendar.JDateChooser();
        combo_tenbn = new javax.swing.JComboBox<>();
        txt_dchi1 = new javax.swing.JTextField();
        dsdv = new javax.swing.JLabel();
        dsdv_chon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_dsdv = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_dsdv_chon = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_bs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_bs.setText("Bác sĩ khám");

        lb_tenbn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_tenbn.setText("Tên bệnh nhân");

        lb_nkham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_nkham.setText("Ngày khám");

        lb_yckham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_yckham.setText("Yêu cầu khám");

        lb_kluan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_kluan.setText("Kết luận");

        combo_tenbs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btn_kham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_kham.setText("Thêm");

        combo_tenbn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        dsdv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dsdv.setText("Danh sách dịch vụ");

        dsdv_chon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dsdv_chon.setText("Danh sách dịch vụ bác sĩ chọn");

        tb_dsdv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên dịch vụ"
            }
        ));
        jScrollPane1.setViewportView(tb_dsdv);

        tb_dsdv_chon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên dịch vụ", "Số lượng"
            }
        ));
        jScrollPane2.setViewportView(tb_dsdv_chon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dsdv)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dsdv_chon)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_bs)
                            .addComponent(lb_tenbn)
                            .addComponent(lb_kluan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo_tenbs, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo_tenbn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_yckham)
                                    .addComponent(lb_nkham))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(date_nkham, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_yckham, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_dchi1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(btn_kham, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_bs)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(date_nkham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_nkham, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_tenbs, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tenbn)
                    .addComponent(lb_yckham)
                    .addComponent(txt_yckham, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_tenbn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_kluan)
                    .addComponent(txt_dchi1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dsdv_chon)
                    .addComponent(dsdv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btn_kham, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietKhamBenhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietKhamBenhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietKhamBenhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietKhamBenhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ChiTietKhamBenhGUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ChiTietKhamBenhGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kham;
    private javax.swing.JComboBox<String> combo_tenbn;
    private javax.swing.JComboBox<String> combo_tenbs;
    private com.toedter.calendar.JDateChooser date_nkham;
    private javax.swing.JLabel dsdv;
    private javax.swing.JLabel dsdv_chon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_bs;
    private javax.swing.JLabel lb_kluan;
    private javax.swing.JLabel lb_nkham;
    private javax.swing.JLabel lb_tenbn;
    private javax.swing.JLabel lb_yckham;
    private javax.swing.JTable tb_dsdv;
    private javax.swing.JTable tb_dsdv_chon;
    private javax.swing.JTextField txt_dchi1;
    private javax.swing.JTextField txt_yckham;
    // End of variables declaration//GEN-END:variables
}
