/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cau_2.GUI;

import Cau_2.BUS.BacSiBUS;
import Cau_2.BUS.BenhNhanBUS;
import Cau_2.BUS.KhamBenhBUS;
import Cau_2.DTO.KhamBenhDTO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author trant
 */
public class DatLichKhamGUI extends javax.swing.JFrame {
    
    private final BacSiBUS bacSiBUS;
    private final BenhNhanBUS benhNhanBUS;
    private final KhamBenhBUS khamBenhBUS;
    
    /**
     * Creates new form BenhNhanGUI
     * @throws java.sql.SQLException
     */
    public DatLichKhamGUI() throws SQLException {
        this.bacSiBUS = new BacSiBUS();
        this.benhNhanBUS = new BenhNhanBUS();
        this.combo_tenbs = new JComboBox<>();
        this.khamBenhBUS = new KhamBenhBUS();
        initComponents();
        
        txt_mabn.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    try {
                        hienThiTenBN(txt_mabn.getText());
                    } catch (SQLException ex) {
                        Logger.getLogger(DatLichKhamGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        
        loadTenBS();
    }
    
    private void hienThiTenBN(String mabn) throws SQLException {
        String tenbn = benhNhanBUS.layTenBN(mabn);
        if (tenbn != null) {
            txt_tenbn.setText(tenbn);
            txt_tenbn.setEditable(false);
        }
        else {
            JOptionPane.showMessageDialog(null, "Bệnh nhân chưa đăng ký", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            txt_tenbn.setText("");
        }
    }
    
    private void loadTenBS() throws SQLException {
        List<String> danhSachTenBS = bacSiBUS.layDSTenBS();
        combo_tenbs.removeAllItems();
        for (String tenBS : danhSachTenBS) {
            combo_tenbs.addItem(tenBS);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_mabn = new javax.swing.JLabel();
        lb_tenbn = new javax.swing.JLabel();
        lb_nkham = new javax.swing.JLabel();
        lb_yc = new javax.swing.JLabel();
        lb_bs = new javax.swing.JLabel();
        txt_mabn = new javax.swing.JTextField();
        txt_tenbn = new javax.swing.JTextField();
        txt_yckham = new javax.swing.JTextField();
        combo_tenbs = new javax.swing.JComboBox<>();
        btn_datlich = new javax.swing.JButton();
        date_nkham = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_mabn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_mabn.setText("Mã bệnh nhân");

        lb_tenbn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_tenbn.setText("Tên bệnh nhân");

        lb_nkham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_nkham.setText("Ngày khám");

        lb_yc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_yc.setText("Yêu cầu khám");

        lb_bs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_bs.setText("Bác sĩ khám");

        combo_tenbs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btn_datlich.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_datlich.setText("Đặt lịch khám");
        btn_datlich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datlichActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_mabn)
                            .addComponent(lb_tenbn)
                            .addComponent(lb_nkham)
                            .addComponent(lb_yc)
                            .addComponent(lb_bs))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_tenbs, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_yckham, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_nkham, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tenbn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mabn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btn_datlich, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_mabn)
                    .addComponent(txt_mabn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tenbn)
                    .addComponent(txt_tenbn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(date_nkham, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(lb_nkham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_yc)
                    .addComponent(txt_yckham, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_bs)
                    .addComponent(combo_tenbs, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_datlich, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_datlichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datlichActionPerformed
        
        String mabn = txt_mabn.getText();
        String tenbs = (String) combo_tenbs.getSelectedItem();
        String makb = null;
        String mabs = null;
        boolean flag = true;
        
        try {
            makb = khamBenhBUS.layMaKB();
        } catch (SQLException ex) {
            Logger.getLogger(DatLichKhamGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            mabs = bacSiBUS.layMaBS(tenbs);
        } catch (SQLException ex) {
            Logger.getLogger(DatLichKhamGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Date seletedDate = date_nkham.getDate();
        LocalDate nkham = null;
        if (seletedDate == null || seletedDate.before(Date.from(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant()))) {
            flag = false;
        }
        else {
            nkham = seletedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }
        
        String yckham = txt_yckham.getText();
        if (yckham.equals("")) {
            flag = false;
        }
        
        try {
            if (flag) {
                KhamBenhDTO kb = new KhamBenhDTO(makb, mabn, mabs, nkham, yckham, null, 0);
                KhamBenhBUS bus = new KhamBenhBUS();

                if (bus.addKhamBenh(kb)) {
                    JOptionPane.showMessageDialog(this, "Đặt lịch khám thành công!");
                    clearLK();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Đặt lịch khám không thành công!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_datlichActionPerformed

    private void clearLK(){
        txt_mabn.setText("");
        txt_tenbn.setText("");
        txt_yckham.setText("");
        date_nkham.setDate(null);
        combo_tenbs.setSelectedIndex(0);
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatLichKhamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatLichKhamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatLichKhamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatLichKhamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new DatLichKhamGUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DatLichKhamGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_datlich;
    private javax.swing.JComboBox<String> combo_tenbs;
    private com.toedter.calendar.JDateChooser date_nkham;
    private javax.swing.JLabel lb_bs;
    private javax.swing.JLabel lb_mabn;
    private javax.swing.JLabel lb_nkham;
    private javax.swing.JLabel lb_tenbn;
    private javax.swing.JLabel lb_yc;
    private javax.swing.JTextField txt_mabn;
    private javax.swing.JTextField txt_tenbn;
    private javax.swing.JTextField txt_yckham;
    // End of variables declaration//GEN-END:variables
}
