/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cau_4.view;

import Cau_4.model.Sach;
import Cau_4.model.DSSach;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trant
 */
public class qlsach_frame extends javax.swing.JFrame {

    private DSSach ds = new DSSach();
    private String tenFile = "./src/Cau_4/data/danh_sach_sach";

    /**
     * Creates new form qlsach_frame
     */
    public qlsach_frame() {
        initComponents();
        taiDanhSachTuFile();
        table.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            // Lấy chỉ số của hàng được click
            int selectedRow = table.getSelectedRow();
            // Kiểm tra nếu chỉ số hàng được chọn hợp lệ
            if (selectedRow != -1) {
                // Lấy giá trị từ bảng và hiển thị trên các JTextField
                text_ma.setText(table.getValueAt(selectedRow, 0).toString());
                text_ten.setText(table.getValueAt(selectedRow, 1).toString());
                text_tacgia.setText(table.getValueAt(selectedRow, 2).toString());
                text_nxb.setText(table.getValueAt(selectedRow, 3).toString());
                text_gia.setText(table.getValueAt(selectedRow, 4).toString());
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lb_ma = new javax.swing.JLabel();
        lb_ten = new javax.swing.JLabel();
        lb_gia = new javax.swing.JLabel();
        lb_tacgia = new javax.swing.JLabel();
        lb_nxb = new javax.swing.JLabel();
        text_ma = new javax.swing.JTextField();
        text_ten = new javax.swing.JTextField();
        text_gia = new javax.swing.JTextField();
        text_nxb = new javax.swing.JTextField();
        text_tacgia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        btn_tim = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thông tin sách");

        lb_ma.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_ma.setText("Mã sách");

        lb_ten.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_ten.setText("Tên sách");

        lb_gia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_gia.setText("Giá");

        lb_tacgia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_tacgia.setText("Tác giả");

        lb_nxb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_nxb.setText("Nhà xuất bản");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Tác giả", "NXB", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(0).setPreferredWidth(60);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(1).setPreferredWidth(240);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(2).setPreferredWidth(150);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(3).setPreferredWidth(130);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_tim.setText("Tìm");
        btn_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timActionPerformed(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_ma)
                                    .addComponent(lb_ten)
                                    .addComponent(lb_gia))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_ten, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(text_gia)
                                    .addComponent(text_ma))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_nxb)
                                    .addComponent(lb_tacgia)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_tacgia, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(text_nxb)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ma)
                    .addComponent(text_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_tacgia)
                    .addComponent(text_tacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_nxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_ten)
                        .addComponent(lb_nxb)
                        .addComponent(text_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_gia)
                    .addComponent(text_gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // thêm sách
        int ma, gia;
        boolean flag = false;
        String ma_txt =text_ma.getText();
        String ten = text_ten.getText();
        String tacgia = text_tacgia.getText();
        String nxb = text_nxb.getText();
        String gia_txt = text_gia.getText();
        
        if (ma_txt.isEmpty() || ten.isEmpty() || tacgia.isEmpty() || nxb.isEmpty() || gia_txt.isEmpty()){
            JOptionPane.showMessageDialog(this, "Không nhập đủ thông tin");
        }
        else {
            try {
                gia = Integer.parseInt(gia_txt);
                ma = Integer.parseInt(ma_txt);
            } catch (NumberFormatException e) {
                ma = 0;
                gia = 0;
                flag = true;
                JOptionPane.showMessageDialog(null, "Mã hoặc giá nhập không phải là số!");
            }
            if (flag == false) {
                Sach sach = new Sach(ma, ten, tacgia, nxb, gia);
                ds.Themsach(sach);

                DefaultTableModel model = (DefaultTableModel) table.getModel();
                clearTextField();
                CapNhatBang();
            }
        }   
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        if (text_ma.getText().isEmpty()) return;
        int ma = Integer.parseInt(text_ma.getText());
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa không?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            ds.XoaSach(ma);
            clearTextField();
            CapNhatBang();
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        int maSach = Integer.parseInt(text_ma.getText());
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn sửa không?", "Xác nhận sửa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String tenSach = text_ten.getText();
            String tacGia = text_tacgia.getText();
            String nxb = text_nxb.getText();
            int gia = Integer.parseInt(text_gia.getText());

            Sach sachSua = new Sach(maSach, tenSach, tacGia, nxb, gia);

            ds.SuaSach(sachSua);

            CapNhatBang();

            JOptionPane.showMessageDialog(null, "Đã sửa thông tin sách", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        luuDanhSachVaoFile();
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timActionPerformed
        int ma = Integer.parseInt(text_ma.getText());
        if (ds.TimSach(ma)) {
            Sach sach = ds.getSach(ma);
            text_ten.setText(sach.getTenSach());
            text_tacgia.setText(sach.getTacGia());
            text_nxb.setText(sach.getNXB());
            text_gia.setText(String.valueOf(sach.getGia()));
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy sách có mã " + ma);
        }
        
    }//GEN-LAST:event_btn_timActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        clearTextField();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        int luaChon = JOptionPane.showConfirmDialog(
				this, 
				"Bạn có muốn thoát khỏi chương trình?",
				"Exit",
				JOptionPane.YES_NO_OPTION);
		if (luaChon == JOptionPane.YES_OPTION) {
			System.exit(0);
		}
    }//GEN-LAST:event_btn_thoatActionPerformed

    
    public void luuDanhSachVaoFile() {
        try {
            File file = new File(tenFile);
            if (!file.exists()) {
                // Nếu thư mục chứa file không tồn tại, tạo thư mục mới
                File parentDir = file.getParentFile();
                if (!parentDir.exists()) {
                    boolean dirCreated = parentDir.mkdirs();
                    if (!dirCreated) {
                        JOptionPane.showMessageDialog(this, "Không thể tạo thư mục mới.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
                // Nếu file không tồn tại, tạo file mới
                boolean created = file.createNewFile();
                if (!created) {
                    JOptionPane.showMessageDialog(this, "Không thể tạo file mới.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            FileOutputStream fos = new FileOutputStream(tenFile);
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            // Ghi danh sách sách vào file
            for (Sach s : ds.getDssach()) {
                oos.writeObject(s);
            }
            oos.close();
            JOptionPane.showMessageDialog(this, "Đã lưu danh sách sách vào file.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } 
        catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi lưu dữ liệu vào file.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void taiDanhSachTuFile() {
        try {
            File file = new File(tenFile);
            if (!file.exists()) {
                return;
            }

            FileInputStream fis = new FileInputStream(file);
            ObjectInputStream ois = new ObjectInputStream(fis);
            // Đọc các đối tượng từ file và thêm vào danh sách
            while (true) {
                try {
                    Sach s = (Sach) ois.readObject();
                    ds.Themsach(s);
                } catch (EOFException e) {
                    break;
                }
            }
            ois.close();

            CapNhatBang();

        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu từ file.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void CapNhatBang() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        List<Sach> sachList = ds.getDssach(); // Lấy danh sách sách từ DSSach
        for (Sach s : sachList) {
            Object[] row = {s.getMaSach(), s.getTenSach(), s.getTacGia(), s.getNXB(), s.getGia()};
            model.addRow(row);
        }
    }
    
    private void clearTextField(){
        text_ma.setText("");
        text_ten.setText("");
        text_gia.setText("");
        text_tacgia.setText("");
        text_nxb.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(qlsach_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(qlsach_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(qlsach_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(qlsach_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new qlsach_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_tim;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_gia;
    private javax.swing.JLabel lb_ma;
    private javax.swing.JLabel lb_nxb;
    private javax.swing.JLabel lb_tacgia;
    private javax.swing.JLabel lb_ten;
    private javax.swing.JTable table;
    private javax.swing.JTextField text_gia;
    private javax.swing.JTextField text_ma;
    private javax.swing.JTextField text_nxb;
    private javax.swing.JTextField text_tacgia;
    private javax.swing.JTextField text_ten;
    // End of variables declaration//GEN-END:variables
}
