﻿alter session set "_ORACLE_SCRIPT"=true;

CREATE USER QLKB IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, DBA TO QLKB;

ALTER SESSION SET CURRENT_SCHEMA = QLKB;


CREATE TABLE BACSI (
    MABS CHAR(4) PRIMARY KEY,
    TENBS VARCHAR2(20)
);

CREATE TABLE BENHNHAN (
    MABN CHAR(4) PRIMARY KEY,
    TENBN VARCHAR2(20),
    NGSINH DATE,
    DCHI VARCHAR2(50),
    DTHOAI VARCHAR2(10),
    GIOITINH CHAR(4) CHECK (GIOITINH IN ('Nam', 'Nữ'))
);

CREATE TABLE KHAMBENH (
    MAKB CHAR(6) PRIMARY KEY,
    MABN CHAR(4),
    MABS CHAR(4),
    NGAYKHAM DATE,
    YEUCAUKHAM VARCHAR2(50),
    KETLUAN VARCHAR2(100),
    THANHTOAN NUMBER
);

ALTER TABLE KHAMBENH ADD CONSTRAINT chk_thanhtoan CHECK (THANHTOAN IN (0, 1));

ALTER TABLE KHAMBENH ADD CONSTRAINT FK_KB_BN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN);
ALTER TABLE KHAMBENH ADD CONSTRAINT FK_KB_BS FOREIGN KEY (MABS) REFERENCES BACSI(MABS);


CREATE TABLE DICHVU (
    MADV CHAR(6) PRIMARY KEY,
    TENDV VARCHAR2(50),
    DONGIA NUMBER
);

CREATE TABLE THUPHI (
    MAKB CHAR(6),
    MADV CHAR(6),
    SOLUONG INT,
    THANHTIEN NUMBER,
    PRIMARY KEY (MAKB, MADV)
);
ALTER TABLE THUPHI ADD CONSTRAINT FK_TP_KB FOREIGN KEY (MAKB) REFERENCES KHAMBENH(MAKB);
ALTER TABLE THUPHI ADD CONSTRAINT FK_TP_DV FOREIGN KEY (MADV) REFERENCES DICHVU(MADV);


SELECT * FROM BACSI;
SELECT * FROM BENHNHAN;
SELECT * FROM KHAMBENH;
SELECT * FROM DICHVU;
SELECT * FROM THUPHI;

SELECT MAX(MaBN) AS MaxMaBN FROM BENHNHAN;

DROP TABLE THUPHI;
DROP TABLE DICHVU;
DROP TABLE KHAMBENH;
DROP TABLE BENHNHAN;
DROP TABLE BACSI;


INSERT INTO BACSI (MABS, TENBS) VALUES ('0001', 'Bac si 1');
INSERT INTO BACSI (MABS, TENBS) VALUES ('0002', 'Bac si 2');
INSERT INTO BACSI (MABS, TENBS) VALUES ('0003', 'Bac si 3');
INSERT INTO BACSI (MABS, TENBS) VALUES ('0004', 'Bac si 4');
INSERT INTO BACSI (MABS, TENBS) VALUES ('0005', 'Bac si 5');

delete from khambenh where makb = '2';

INSERT INTO DICHVU (MADV, TENDV, DONGIA) VALUES ('000001', 'Dich vu 1', 100000);
INSERT INTO DICHVU (MADV, TENDV, DONGIA) VALUES ('000002', 'Dich vu 2', 150000);
INSERT INTO DICHVU (MADV, TENDV, DONGIA) VALUES ('000003', 'Dich vu 3', 200000);
INSERT INTO DICHVU (MADV, TENDV, DONGIA) VALUES ('000004', 'Dich vu 4', 250000);000
INSERT INTO DICHVU (MADV, TENDV, DONGIA) VALUES ('000008', 'Dich vu 8', 450000);


SELECT TENBN FROM BENHNHAN WHERE MABN = '0003'
